/**
 * `pixelproof retake` — spend another attempt on a run that was rejected
 * (ADR 0020 §3).
 *
 * A top-level command rather than a flag on `generate`. Every one of
 * `--prompt`, `--out`, `--spec`, `--size` and `--provider` comes from the run
 * record, so `generate --retake <id>` would sit on a command whose options
 * mostly do not apply and whose `--out` is mandatory. A command whose flags are
 * exactly the ones that mean something is worth one line in the registry.
 *
 * What this command is *not*: it is not a second implementation of the judged
 * run. It reuses `prepareGeneration` from `generate` so attempt *n+1* is shaped
 * exactly the way attempt *n* was, and `completeJudgedRun` so recording, the
 * mechanical retake loop, exhaustion and the checklist all behave identically to
 * a first attempt. The only thing it adds is reading the run back and building
 * the corrections from what that run recorded.
 *
 * ## Exit codes
 *
 * - `2` — a new checklist is outstanding. Never a pass.
 * - `1` — rejected, refused, or errored.
 *
 * There is no `0`: a retake ends in a pending judgement or in a rejection, never
 * in an acceptance, because acceptance is `judge submit`'s to grant.
 */

import { readFile } from 'node:fs/promises';
import path from 'node:path';

import { correctionsFor } from '../../../core/generation/correction.mjs';
import {
  HOST_JUDGE,
  PendingError,
  boundOf,
  openRetakeableRun,
  parseDeadline,
  retakesLeft,
} from '../../../core/judge/index.mjs';
import { attemptStem } from '../../../core/run/index.mjs';
import { loadV1Spec, mechanicalBlock } from '../../../core/spec/load-v1.mjs';
import { resolveDimensions } from '../../../core/spec/dimensions.mjs';
import { printUsage, printUsageError } from '../format-errors.mjs';
import { printCorrections, printJudgeError } from '../format-judge.mjs';
import { printVerificationResult, printWarning } from '../format-verification.mjs';
import { attemptTarget, completeJudgedRun } from '../judged-run.mjs';
import { parseArguments } from '../parse.mjs';
import { prepareGeneration } from './generate.mjs';
import { verifyImage } from './verify.mjs';

const defaultOutput = globalThis.console;

export const RETAKE_USAGE = `pixelproof retake

Usage:
  pixelproof retake --run <id> [--run-dir <path>] [--judge-deadline <dur>]

Options:
  --run <id>               The rejected run to spend another attempt on (required)
  --run-dir <path>         Run root; also PIXELPROOF_RUN_ROOT (default .pixelproof/runs)
  --judge-deadline <dur>   How long the new checklist stays answerable
  -h, --help               Show this help

A retake is a new numbered attempt inside the same run directory. The prompt,
spec, provider, size and output come from the run record; the correction is
assembled from what the rejected attempt actually recorded and is never invented.

Refused with exit 1 and a named reason for a run that is terminal, has an
outstanding judgement, asked for no judge, or has spent its retake bound.
Nothing is promoted on exhaustion: --out stays empty and the report lists every
attempt.

Exit codes: 1 rejected or refused, 2 an outstanding judgement. Exit 2 is never
a pass.
`;

const RETAKE_FLAGS = new Map([['-h', 'help'], ['--help', 'help']]);
const RETAKE_VALUED = new Set(['--run', '--run-dir', '--judge-deadline']);

/** Read an attempt record back. It is this build's own file, written atomically. */
async function readAttempt(directory, number) {
  const file = path.join(directory, `${attemptStem(number)}.json`);
  return JSON.parse(await readFile(file, 'utf8'));
}

/**
 * Everything the recorded run says about how to generate again.
 *
 * A run that cannot be re-driven is refused here rather than half-generated. In
 * practice this is unreachable through the CLI — `verify --judge host` takes no
 * `--retakes` and `generate` refuses `--retakes` with the svg provider — so it
 * guards a run record edited by hand or written by a future build, and says
 * which field is missing rather than throwing somewhere further down.
 */
function generationPlan(run, { runId }) {
  const resolved = run.resolved ?? {};
  const provider = resolved.provider ?? null;
  const prompt = resolved.prompt ?? null;

  if (provider !== 'codex') {
    throw new Error(
      `Run ${runId} was generated by ${provider === null ? 'no recorded provider' : `the ${provider} provider`}, `
        + 'which a corrected prompt cannot re-drive. Only a prompt-driven provider can be retaken.',
    );
  }
  if (typeof prompt !== 'string' || prompt.trim() === '') {
    throw new Error(`Run ${runId} recorded no prompt, so there is nothing to correct and re-send.`);
  }

  return { provider, prompt, out: resolved.out ?? null, specPath: resolved.spec ?? null, size: resolved.size ?? null };
}

/** Run the retake over `argv` (already stripped of node and `retake`). */
export async function runRetake(argv = [], { output = defaultOutput } = {}) {
  let options;
  try {
    options = parseArguments(argv, {
      flags: RETAKE_FLAGS,
      valued: RETAKE_VALUED,
      defaults: { help: false },
      camelCase: true,
    });
  } catch (error) {
    printUsageError(error.message, RETAKE_USAGE, output);
    return 1;
  }

  if (options.help) {
    printUsage(RETAKE_USAGE, output);
    return 0;
  }
  if (!options.run) {
    printUsageError('--run <id> is required: a retake names the run it continues', RETAKE_USAGE, output);
    return 1;
  }

  try {
    const opened = await openRetakeableRun({ runId: options.run, runDir: options.runDir ?? null });
    const { run, directory, attempt } = opened;
    const plan = generationPlan(run, { runId: opened.runId });

    // A subprocess-judged run never waits for an operator: its verdict arrives
    // in the process that generated the attempt, so a rejection is corrected and
    // retaken there (ADR 0021 §7). Reaching this command means the run was
    // interrupted, and resuming it would mean re-judging attempt n+1 through a
    // registry this command does not build. Refused by name rather than resumed
    // as if it were a host run, which would issue a checklist nobody asked for.
    const judgedBy = run.judge?.kind ?? HOST_JUDGE;
    if (judgedBy !== HOST_JUDGE) {
      throw new Error(
        `Run ${opened.runId} is judged by a ${judgedBy} panel, which retakes inside \`generate\` rather than here. `
          + 'Close it with `pixelproof judge abandon` and run `generate` again.',
      );
    }

    // The spec is re-read rather than remembered: the checklist for the new
    // attempt is built from it, and a spec that moved under the run must change
    // the checksDigest rather than be silently replayed from a stale copy.
    if (plan.specPath === null) {
      throw new Error(`Run ${opened.runId} recorded no spec, so there are no assertions to judge a retake against.`);
    }
    const spec = await loadV1Spec(plan.specPath);
    const assertions = spec.semantic ?? [];
    if (assertions.length === 0) {
      throw new Error(`${plan.specPath} declares no "semantic" assertions; there is nothing for a host to judge.`);
    }

    const dimensions = plan.size ?? resolveDimensions(null, mechanicalBlock(spec));
    const corrections = correctionsFor(await readAttempt(directory, attempt - 1));

    output.log(`Run ${opened.runId}: attempt ${attempt} of ${boundOf(run)}, `
      + `${retakesLeft(run)} left after this one is recorded.`);
    printCorrections(corrections, { attempt: attempt - 1 }, output);
    output.log('');

    const target = attemptTarget(directory, plan.out ?? '.png', attempt);

    const generateAttempt = async (outPath, attemptCorrections, correctingAttempt) => {
      const { generate, request } = await prepareGeneration({
        provider: plan.provider,
        options: { prompt: plan.prompt, out: outPath },
        dimensions,
        verificationSpec: spec,
        corrections: attemptCorrections,
        correctingAttempt,
      });

      const generation = await generate(request);
      output.log(`Provider: ${plan.provider}`);
      output.log(`Output: ${generation.outputPath}`);
      for (const warning of generation.warnings ?? []) printWarning(warning);

      const verification = await verifyImage({
        filePath: generation.outputPath,
        spec,
        specPath: plan.specPath,
      });
      printVerificationResult(verification);
      return verification;
    };

    const verification = await generateAttempt(target, corrections, attempt - 1);

    return completeJudgedRun(directory, {
      run,
      artifactPath: target,
      copy: false,
      verification,
      spec,
      specPath: plan.specPath,
      assertions,
      deadlineMs: options.judgeDeadline
        ? parseDeadline(options.judgeDeadline)
        : run.resolved?.deadlineMs ?? undefined,
      out: plan.out,
      attempt,
      output,
      regenerate: async ({ attempt: next, corrections: nextCorrections }) => {
        const nextTarget = attemptTarget(directory, plan.out ?? '.png', next);
        return {
          artifactPath: nextTarget,
          verification: await generateAttempt(nextTarget, nextCorrections, next - 1),
        };
      },
    });
  } catch (error) {
    if (error instanceof PendingError) {
      printJudgeError(error, output);
      return 1;
    }
    printUsageError(error.message, RETAKE_USAGE, output);
    return 1;
  }
}

export default runRetake;
